server:
  servlet:
    context-path: /ds
  port: 8081
logging:
  level:
    com.leadingsoft.ds: debug
spring:
  datasource:
    url: 'jdbc:mysql://10.10.1.100/ds?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai'
    username: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    password: 'Abc.123456'
    hikari:
      connection-test-query: select 1
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    hibernate:
      use-new-id-generator-mappings: true
  cache:
    cache-names:
    - svcCache
    - appCache
    - resultCache
    jcache:
      config: classpath:cache.xml